window.onbeforeunload=stopChannel;var SMessageChannel="FSMessage",SMsgCallback="FSMessageCallBack",AccbookID="0",loginCode="",loginpassword="",channel=null,userID=null,cachedUsers=null,userName=null,LoginUserMethods=null,MessageManage=null,connectionInfo=null;setTimeout("loadChatRoom()",127);function newGuid(){for(var a="",b=1;32>=b;b++){var c=Math.floor(16*Math.random()).toString(16),a=a+c;if(8==b||12==b||16==b||20==b)a+="-"}return a}
function getUserList(a){a=null==a?!1:a;var b=LoginUserMethods.GetUserList();return null!=b&&null!=b.result?b.result:a?null:b}function loadChatRoom(){openLoginDialog()}function Login(){openLoginDialog()}
function startChannel(){if(null==userID)throw Error("\u8fd8\u6ca1\u767b\u5f55!");var a=newGuid(),b=SMessageChannel+AccbookID;channel=new ClientChannel(a,b,connectionInfo);b=new ClientCallback(channel,SMsgCallback,function(a){if(null!=a)if(null!=a.notificationType){var b=a.notificationType,e=a.fromusrname,f=a.datetime;if("user_login"==b||"user_logout"==b)loadUsers(),addMessage(e,"user_login"==b?"\u767b\u5f55\u4e86\uff01":"\u9000\u51fa\u4e86\uff01",f,!1);else if("message"==b)b=a.msgtype,addMessage(e,
a.message,f,"2"==b);else if("cmd"==b){var g=a.cmd,b=a.msgtype;addMessage(e,"ring"==g?"\u54cd\u94c3":"\u9707\u52a8",f,"2"==b)}}else null!=a.SessionExpired&&addMessage(null,a.SessionExpired,null,null,!0);return!0},b);0==channel.callbacks.length?channel.connect(b):channel.registerCallback(b);LoginUserMethods.UpdateCurUserCallbackClientID(a)}function stopChannel(){null!=LoginUserMethods&&LoginUserMethods.Logout();null!=channel&&null!=channel.callbackLoop&&channel.closeSession()}
function addMessage(a,b,c,d,e){null==d&&(d=!1);null==e&&(e=!1);if((null!=a||e)&&null!=b){var f=document.createElement("div");f.classname="entry";f.innerHTML=e?'<span class="messagefail">'+b+"</span>":"<b>"+a+"></b> "+c+"<br/>"+(d?"<small><i>(\u5355\u72ec\u8bf4)</i></small> ":"")+b;document.getElementById("chatarea").appendChild(f);f.scrollIntoView(!1)}}
function loadUsers(){var a=getUserList(),b=document.getElementById("userlist");if(null==a)return addMessage(null,"Connection to the server could not be established.",null,!0),stopChannel(),b.innerHTML="[\u6ca1\u6709\u7528\u6237]",!1;if(null!=a.SessionExpired)return addMessage(null,a.SessionExpired,null,null,!0),stopChannel(),b.innerHTML="[\u6ca1\u6709\u7528\u6237]",!1;if(null!=a&&null!=b)if(cachedUsers=a,0<a.length){for(var c=[""],d=0;d<a.length;d++)c.push(a[d].username),c.push("<br />\n");b.innerHTML=
c.join("")}else b.innerHTML="[\u6ca1\u6709\u7528\u6237]"}function sendOnEnter(a){a=a?a:window.event;13==(a.which?a.which:a.keyCode)&&sendMessage()}
function sendMessage(){var a=document.getElementById("messageField");if(null!=channel&&null!=a){var b=a.value.trim();0<b.length&&(b=LoginUserMethods.SendMessageToAll(b),null==b||null==b.result||!0!=b.result?(a="ERROR: your message could not be sent to one or more users. Please try again.",null!=b&&null!=b.SessionExpired&&(stopChannel(),a=b.SessionExpired),addMessage(null,a,null,null,!0)):a.value="")}}
function openPrivateMessageDialog(){var a=document.getElementById("messageField");null!=a&&""!=a.value.trim()&&(populatePrivateMessageUserList(),toggleModal())}function toggleModal(){var a=document.getElementById("modal");a.style.visibility="visible"==a.style.visibility?"hidden":"visible"}
function sendPrivateMessage(){var a=document.getElementById("chosenuser").value.trim();if(""!=a&&a!=userID){toggleModal();var b=document.getElementById("messageField"),c=b.value.trim();0<c.length&&(a=LoginUserMethods.SendMessageToUser(c,a),(a=null==a.result||!0!==a.result)?(b="ERROR: your message could not be sent. Please try again.",null!=a&&null!=a.SessionExpired&&(stopChannel(),b=a.SessionExpired),addMessage(null,b,null,null,!0)):b.value="")}}
function updateChosenUser(){var a=document.getElementById("chosenuser"),b=document.getElementById("privateusers");a.value=b.value}function populatePrivateMessageUserList(){for(var a=document.getElementById("privateusers"),b=a.length;0<=b;b--)a[b]=null;a[a.length]=new Option("\u9009\u62e9\u4e00\u4e2a\u7528\u6237","");for(b=0;b<cachedUsers.length;b++){var c=cachedUsers[b];c.userid!=userID&&(a[a.length]=new Option(c.username,c.userid))}}
function toggleMlogin(){var a=document.getElementById("mlogin");a.style.visibility="visible"==a.style.visibility?"hidden":"visible"}function updateChosenAcc(){var a=document.getElementById("chosenacc"),b=document.getElementById("selectaccs");a.value=b.value}
function updateLoginUser(){var a=document.getElementById("logincode"),b=document.getElementById("loginpassword");AccbookID="0";loginCode=a.value.trim();loginpassword=b.value.trim();""!=loginCode&&toggleMlogin();connectionInfo=getAuth(loginCode,loginpassword);LoginUserMethods=new TLoginUser(connectionInfo);a=LoginUserMethods.GetCurUserJSON();userName=a.result.username;userID=a.result.userid;null!=userID&&(loadUsers(),startChannel());document.getElementById("loginlabel").innerHTML=null!=userName?"<b>\u767b\u5f55\u4e3a:</b> "+
userName:"<b>\u6ca1\u6709\u767b\u5f55!</b>"}function cancelLogin(){loginpassword=loginCode="";stopChannel();toggleMlogin()}function populateAccbookList(){var a=document.getElementById("selectaccs"),b=LoginUserMethods.GetAccListJSON().result.accbooks;a[a.length]=new Option("\u9009\u62e9\u767b\u5f55\u8d26\u5957","");for(var c=0;c<b.length;c++){var d=b[c];a[a.length]=new Option(d.syaccbookname,d.syaccbookcode)}}function openLoginDialog(){toggleMlogin()}
String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s*/,"").replace(/\s*$/,"")});
Date.prototype.pattern=function(a){var b={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":0==this.getHours()%12?12:this.getHours()%12,"H+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),S:this.getMilliseconds()},c={"0":"/u65e5",1:"/u4e00",2:"/u4e8c",3:"/u4e09",4:"/u56db",5:"/u4e94",6:"/u516d"};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length)));/(E+)/.test(a)&&(a=a.replace(RegExp.$1,(1<RegExp.$1.length?2<
RegExp.$1.length?"/u661f/u671f":"/u5468":"")+c[this.getDay()+""]));for(var d in b)RegExp("("+d+")").test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?b[d]:("00"+b[d]).substr((""+b[d]).length)));return a};
