function DSAdmin(l){this.executor=new ServerFunctionExecutor("DSAdmin",l);this.GetPlatformName=function(d,b,c){b=this.executor.executeMethod("GetPlatformName","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],d):b};this.ClearResources=function(d,b,c){b=this.executor.executeMethod("ClearResources","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],d):b};this.FindPackages=function(d,b,c){b=
this.executor.executeMethod("FindPackages","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.FindClasses=function(d,b,c,a,e){a=this.executor.executeMethod("FindClasses","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.PackageName=d,e.ClassPattern=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=
a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.FindMethods=function(d,b,c,a,e,f){e=this.executor.executeMethod("FindMethods","GET",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&null!=e.result&&isArray(e.result)?(a=e.result,f={},f.PackageName=d,f.ClassPattern=b,f.MethodPattern=c,f.result=a[0],null!=e.cacheId&&null!=e.cmdIndex&&(f._cacheId=e.cacheId,f._cmdIndex=e.cmdIndex),f):e};this.CreateServerClasses=function(d,b,c,a){this.executor.executeMethod('"CreateServerClasses"',"POST",[d],b,!1,c,a)};this.DropServerClasses=
function(d,b,c,a){this.executor.executeMethod('"DropServerClasses"',"POST",[d],b,!1,c,a)};this.CreateServerMethods=function(d,b,c,a){this.executor.executeMethod('"CreateServerMethods"',"POST",[d],b,!1,c,a)};this.DropServerMethods=function(d,b,c,a){this.executor.executeMethod('"DropServerMethods"',"POST",[d],b,!1,c,a)};this.GetServerClasses=function(d,b,c){b=this.executor.executeMethod("GetServerClasses","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=
b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.ListClasses=function(d,b,c){b=this.executor.executeMethod("ListClasses","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.DescribeClass=function(d,b,c,a){c=this.executor.executeMethod("DescribeClass","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=
c.result&&isArray(c.result)?(b=c.result,a={},a.ClassName=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.ListMethods=function(d,b,c,a){c=this.executor.executeMethod("ListMethods","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.ClassName=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.DescribeMethod=function(d,b,c,a){c=this.executor.executeMethod("DescribeMethod",
"GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.ServerMethodName=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetServerMethods=function(d,b,c){b=this.executor.executeMethod("GetServerMethods","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};
this.GetServerMethodParameters=function(d,b,c){b=this.executor.executeMethod("GetServerMethodParameters","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetDatabaseConnectionProperties=function(d,b,c){b=this.executor.executeMethod("GetDatabaseConnectionProperties","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},
d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetDSServerName=function(d,b,c){b=this.executor.executeMethod("GetDSServerName","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],d):b};this.ConsumeClientChannel=function(d,b,c,a,e,f,h,g,j){g=this.executor.executeMethod('"ConsumeClientChannel"',"POST",[d,b,c,a,e,f],h,!0,g,j);if(null==h)return null!=g&&null!=g.result&&isArray(g.result)?
(h=g.result,j={},j.ChannelName=d,j.ClientManagerId=b,j.CallbackId=c,j.ChannelNames=a,j.SecurityToken=e,j.ResponseData=f,j.result=h[0],null!=g.cacheId&&null!=g.cmdIndex&&(j._cacheId=g.cacheId,j._cmdIndex=g.cmdIndex),j):g};this.ConsumeClientChannelTimeout=function(d,b,c,a,e,f,h,g,j,k){j=this.executor.executeMethod('"ConsumeClientChannelTimeout"',"POST",[d,b,c,a,e,f,h],g,!0,j,k);if(null==g)return null!=j&&null!=j.result&&isArray(j.result)?(g=j.result,k={},k.ChannelName=d,k.ClientManagerId=b,k.CallbackId=
c,k.ChannelNames=a,k.SecurityToken=e,k.Timeout=f,k.ResponseData=h,k.result=g[0],null!=j.cacheId&&null!=j.cmdIndex&&(k._cacheId=j.cacheId,k._cmdIndex=j.cmdIndex),k):j};this.CloseClientChannel=function(d,b,c,a,e){a=this.executor.executeMethod("CloseClientChannel","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.ChannelId=d,a.SecurityToken=b,a.result=c[0]),a};this.RegisterClientCallbackServer=function(d,b,c,a,e,f,h){f=this.executor.executeMethod("RegisterClientCallbackServer",
"GET",[d,b,c,a],e,!0,f,h);if(null==e)return null!=f&&(null!=f.result&&isArray(f.result))&&(e=f.result,f={},f.ChannelId=d,f.CallbackId=b,f.ChannelNames=c,f.SecurityToken=a,f.result=e[0]),f};this.UnregisterClientCallback=function(d,b,c,a,e,f){e=this.executor.executeMethod("UnregisterClientCallback","GET",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&(null!=e.result&&isArray(e.result))&&(a=e.result,e={},e.ChannelId=d,e.CallbackId=b,e.SecurityToken=c,e.result=a[0]),e};this.BroadcastToChannel=function(d,
b,c,a,e){a=this.executor.executeMethod('"BroadcastToChannel"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.ChannelName=d,a.Msg=b,a.result=c[0]),a};this.BroadcastObjectToChannel=function(d,b,c,a,e){a=this.executor.executeMethod('"BroadcastObjectToChannel"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.ChannelName=d,a.Msg=b,a.result=c[0]),a};this.NotifyCallback=function(d,b,c,a,e,
f){e=this.executor.executeMethod('"NotifyCallback"',"POST",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&null!=e.result&&isArray(e.result)?(a=e.result,f={},f.ClientId=d,f.CallbackId=b,f.Msg=c,f.Response=a[0],f.result=a[1],null!=e.cacheId&&null!=e.cmdIndex&&(f._cacheId=e.cacheId,f._cmdIndex=e.cmdIndex),f):e};this.NotifyObject=function(d,b,c,a,e,f){e=this.executor.executeMethod('"NotifyObject"',"POST",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&null!=e.result&&isArray(e.result)?(a=e.result,f={},f.ClientId=
d,f.CallbackId=b,f.Msg=c,f.Response=a[0],f.result=a[1],null!=e.cacheId&&null!=e.cmdIndex&&(f._cacheId=e.cacheId,f._cmdIndex=e.cmdIndex),f):e}}
function TLoginUser(l){this.executor=new ServerFunctionExecutor("TLoginUser",l);this.GetSysConnectionString=function(d,b,c){b=this.executor.executeMethod("GetSysConnectionString","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],d):b};this.ChangePassword=function(d,b,c,a,e,f,h){a=this.executor.executeMethod("ChangePassword","GET",[d,b,c,a],e,!0,f,h);if(null==e)return null!=a&&(null!=a.result&&isArray(a.result))&&(e=a.result,a={},a.UserCode=
d,a.OldPassword=b,a.NewPassword=c,a.msg=e[0],a.result=e[1]),a};this.UpdateCurUserCallbackClientID=function(d,b,c,a){c=this.executor.executeMethod("CurUserCallbackClientID","POST",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.Value=d,c.result=b[0]),c};this.Logout=function(d,b,c){this.executor.executeMethod("Logout","GET",[],d,!1,b,c)};this.SetUsersToFollow=function(d,b,c,a){this.executor.executeMethod('"SetUsersToFollow"',"POST",[d],b,!1,c,a)};this.SendMessageToFollow=
function(d,b,c,a){c=this.executor.executeMethod("SendMessageToFollow","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.Msg=d,c.result=b[0]),c};this.SendMessageToAll=function(d,b,c,a){c=this.executor.executeMethod("SendMessageToAll","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.Msg=d,c.result=b[0]),c};this.SendMessageToUser=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToUser",
"GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.UserID=b,a.result=c[0]),a};this.SendMessageToDepartment=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToDepartment","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.DepartmentID=b,a.result=c[0]),a};this.SendMessageToGroup=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToGroup","GET",[d,b],c,!0,
a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.GroupID=b,a.result=c[0]),a};this.SendCMDToFollow=function(d,b,c,a){c=this.executor.executeMethod("SendCMDToFollow","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.cmdStr=d,c.result=b[0]),c};this.SendCMDToAll=function(d,b,c,a){c=this.executor.executeMethod("SendCMDToAll","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&
(b=c.result,c={},c.cmdStr=d,c.result=b[0]),c};this.SendCMDToUser=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToUser","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.UserID=b,a.result=c[0]),a};this.SendCMDToDepartment=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToDepartment","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.DepartmentID=b,
a.result=c[0]),a};this.SendCMDToGroup=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToGroup","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.GroupID=b,a.result=c[0]),a};this.SendMgrMessage=function(d,b,c,a,e){a=this.executor.executeMethod("SendMgrMessage","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.itype=d,a.Msg=b,a.result=c[0]),a};this.GetAccList=function(d,
b,c){b=this.executor.executeMethod("GetAccList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetCurUserInfo=function(d,b,c){b=this.executor.executeMethod("GetCurUserInfo","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=
b.cmdIndex),d):b};this.ListOfLoginUser=function(d,b,c){b=this.executor.executeMethod("ListOfLoginUser","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.ListOfAllLoginUser=function(d,b,c){b=this.executor.executeMethod("ListOfAllLoginUser","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=
b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetClassList=function(d,b,c){b=this.executor.executeMethod("GetClassList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetAutoCodeFields=function(d,b,c){b=this.executor.executeMethod("GetAutoCodeFields","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&
isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetModuleData=function(d,b,c){b=this.executor.executeMethod("GetModuleData","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.RefreshGlobeVar=function(d,b,c){b=this.executor.executeMethod("RefreshGlobeVar","GET",[],
d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetModuleRight=function(d,b,c){b=this.executor.executeMethod("GetModuleRight","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetAccInforJSON=function(d,b,c){b=
this.executor.executeMethod("GetAccInforJSON","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetAccListJSON=function(d,b,c){b=this.executor.executeMethod("GetAccListJSON","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),
d):b};this.GetCurUserJSON=function(d,b,c){b=this.executor.executeMethod("GetCurUserJSON","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetUserList=function(d,b,c){b=this.executor.executeMethod("GetUserList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&
(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetAllUserList=function(d,b,c){b=this.executor.executeMethod("GetAllUserList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetClassListJO=function(d,b,c){b=this.executor.executeMethod("GetClassListJO","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=
b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetAutoCodeFieldsJO=function(d,b,c){b=this.executor.executeMethod("GetAutoCodeFieldsJO","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetModuleDataJO=function(d,b,c){b=this.executor.executeMethod("GetModuleDataJO","GET",[],d,!0,b,c);if(null==d)return null!=
b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.RefreshGlobeVarJO=function(d,b,c){b=this.executor.executeMethod("RefreshGlobeVarJO","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetModuleRightJO=function(d,b,c){b=this.executor.executeMethod("GetModuleRightJO",
"GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetDepartmentAndUsersList=function(d,b,c){b=this.executor.executeMethod("GetDepartmentAndUsersList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.UserIdToName=
function(d,b,c,a){c=this.executor.executeMethod("UserIdToName","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.UserId=d,c.result=b[0]),c};this.GetServerInfo=function(d,b,c){b=this.executor.executeMethod("GetServerInfo","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetFtpSetting=function(d,b,c){b=
this.executor.executeMethod("GetFtpSetting","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetMailSetting=function(d,b,c){b=this.executor.executeMethod("GetMailSetting","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),
d):b};this.GetSmsSetting=function(d,b,c){b=this.executor.executeMethod("GetSmsSetting","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetWorkFlowServerList=function(d,b,c){b=this.executor.executeMethod("GetWorkFlowServerList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&
null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetSmsServerList=function(d,b,c){b=this.executor.executeMethod("GetSmsServerList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b}}
function TSyAccBook(l){this.executor=new ServerFunctionExecutor("TSyAccBook",l);this.GetAllAccBook=function(d,b,c){b=this.executor.executeMethod("GetAllAccBook","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetActiveAccBook=function(d,b,c){b=this.executor.executeMethod("GetActiveAccBook","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&
isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetAllAccBookJO=function(d,b,c){b=this.executor.executeMethod("GetAllAccBookJO","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetActiveAccBookJO=function(d,b,c){b=this.executor.executeMethod("GetActiveAccBookJO",
"GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b}}
function TServerDataSet(l){this.executor=new ServerFunctionExecutor("TServerDataSet",l);this.GetInitResult=function(d,b,c,a){c=this.executor.executeMethod("GetInitResult","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.ClassCode=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.Open=function(d,b,c,a,e){a=this.executor.executeMethod('"Open"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&
null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Update=function(d,b,c,a,e){a=this.executor.executeMethod('"Update"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Delete=function(d,b,
c,a,e){a=this.executor.executeMethod('"Delete"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.DeleteDetail=function(d,b,c,a,e){a=this.executor.executeMethod('"DeleteDetail"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=
a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.CmdExec=function(d,b,c,a,e){a=this.executor.executeMethod('"CmdExec"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Check=function(d,b,c,a,e){a=this.executor.executeMethod('"Check"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=
a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.CloseOff=function(d,b,c,a,e){a=this.executor.executeMethod('"CloseOff"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Revoke=function(d,
b,c,a,e){a=this.executor.executeMethod('"Revoke"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Tally=function(d,b,c,a,e){a=this.executor.executeMethod('"Tally"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&
null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.ExecSQL=function(d,b,c,a){c=this.executor.executeMethod('"ExecSQL"',"POST",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.Stream=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.ValidateData=function(d,b,c,a,e){a=this.executor.executeMethod('"ValidateData"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&
isArray(a.result)?(c=a.result,e={},e.Stream=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.QueryOpen=function(d,b,c,a){c=this.executor.executeMethod("QueryOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QueryExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QueryExecSQL",
"GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QuerySysOpen=function(d,b,c,a){c=this.executor.executeMethod("QuerySysOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};
this.QuerySysExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QuerySysExecSQL","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c}}
function TServerQuery(l){this.executor=new ServerFunctionExecutor("TServerQuery",l);this.QueryOpen=function(d,b,c,a){c=this.executor.executeMethod("QueryOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QueryExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QueryExecSQL","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=
c.result&&isArray(c.result))&&(b=c.result,c={},c.SQLText=d,c.result=b[0]),c};this.ExecSQL=function(d,b,c,a,e){a=this.executor.executeMethod('"ExecSQL"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.SQLText=d,a.Parameters=b,a.result=c[0]),a};this.QuerySysOpen=function(d,b,c,a){c=this.executor.executeMethod("QuerySysOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=
b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QuerySysExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QuerySysExecSQL","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.SQLText=d,c.result=b[0]),c};this.SysExecSQL=function(d,b,c,a,e){a=this.executor.executeMethod('"SysExecSQL"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.SQLText=
d,a.Parameters=b,a.result=c[0]),a}}
function TJServerDataSet(l){this.executor=new ServerFunctionExecutor("TJServerDataSet",l);this.GetInitResult=function(d,b,c,a){c=this.executor.executeMethod("GetInitResult","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.ClassCode=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.Open=function(d,b,c,a,e){a=this.executor.executeMethod('"Open"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=
a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Update=function(d,b,c,a,e){a=this.executor.executeMethod('"Update"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Delete=function(d,b,
c,a,e){a=this.executor.executeMethod('"Delete"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.DeleteDetail=function(d,b,c,a,e){a=this.executor.executeMethod('"DeleteDetail"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=
a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.ValidateData=function(d,b,c,a,e){a=this.executor.executeMethod('"ValidateData"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.CmdExec=function(d,b,c,a,e){a=this.executor.executeMethod('"CmdExec"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=
a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Check=function(d,b,c,a,e){a=this.executor.executeMethod('"Check"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.CloseOff=function(d,b,
c,a,e){a=this.executor.executeMethod('"CloseOff"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Revoke=function(d,b,c,a,e){a=this.executor.executeMethod('"Revoke"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&
null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.Tally=function(d,b,c,a,e){a=this.executor.executeMethod('"Tally"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.ExecSQL=function(d,b,c,a){c=this.executor.executeMethod('"ExecSQL"',"POST",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&
isArray(c.result)?(b=c.result,a={},a.Json=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QueryOpen=function(d,b,c,a){c=this.executor.executeMethod("QueryOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QueryExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QueryExecSQL",
"GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QuerySysOpen=function(d,b,c,a){c=this.executor.executeMethod("QuerySysOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};
this.QuerySysExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QuerySysExecSQL","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c}}
function TJServerQuery(l){this.executor=new ServerFunctionExecutor("TJServerQuery",l);this.QueryOpen=function(d,b,c,a){c=this.executor.executeMethod("QueryOpen","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QueryUpdate=function(d,b,c,a,e){a=this.executor.executeMethod('"QueryUpdate"',"POST",[d,b],c,!0,a,e);if(null==c)return null!=
a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.Json=d,e.ClassCode=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.QueryExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QueryExecSQL","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.SQLText=d,c.result=b[0]),c};this.QuerySysOpen=function(d,b,c,a){c=this.executor.executeMethod("QuerySysOpen","GET",[d],b,!0,c,a);if(null==b)return null!=
c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.SQLText=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.QuerySysExecSQL=function(d,b,c,a){c=this.executor.executeMethod("QuerySysExecSQL","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.SQLText=d,c.result=b[0]),c}}
function TWorkFlowServer(l){this.executor=new ServerFunctionExecutor("TWorkFlowServer",l);this.ServerWorkFlowStartJSON=function(d,b,c,a){c=this.executor.executeMethod('"ServerWorkFlowStartJSON"',"POST",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.jsonValue=d,c.result=b[0]),c};this.ServerWorkFlowStart=function(d,b,c,a,e,f,h,g,j,k,l){k=this.executor.executeMethod("ServerWorkFlowStart","GET",[d,b,c,a,e,f,h,g],j,!0,k,l);if(null==j)return null!=k&&(null!=
k.result&&isArray(k.result))&&(j=k.result,k={},k.FlowDefID=d,k.Subject=b,k.Content=c,k.BusWindow=a,k.BusCode=e,k.Rank=f,k.PrjID=h,k.Report=g,k.result=j[0]),k};this.ServerWorkFlowExecJSON=function(d,b,c,a){c=this.executor.executeMethod('"ServerWorkFlowExecJSON"',"POST",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.jsonValue=d,c.result=b[0]),c};this.ServerWorkFlowExec=function(d,b,c,a,e,f,h,g,j){g=this.executor.executeMethod('"ServerWorkFlowExec"',
"POST",[d,b,c,a,e,f],h,!0,g,j);if(null==h)return null!=g&&(null!=g.result&&isArray(g.result))&&(h=g.result,g={},g.FlowDefID=d,g.WorkInsID=b,g.TaskInsID=c,g.TskStatus=a,g.TskComments=e,g.VariableList=f,g.result=h[0]),g};this.GetTaskList=function(d,b,c,a,e,f){e=this.executor.executeMethod("GetTaskList","GET",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&null!=e.result&&isArray(e.result)?(a=e.result,f={},f.AUserID=d,f.ACompletedState=b,f.AOtherCondition=c,f.result=a[0],null!=e.cacheId&&null!=e.cmdIndex&&
(f._cacheId=e.cacheId,f._cmdIndex=e.cmdIndex),f):e};this.GetLogList=function(d,b,c,a,e){a=this.executor.executeMethod("GetLogList","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.ALogFilterType=d,a.AFilterKey=b,a.result=c[0]),a};this.GetDiagram=function(d,b,c,a,e){a=this.executor.executeMethod("GetDiagram","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.ADiagramType=d,a.ADiagramKey=b,
a.result=c[0]),a};this.GetTaskdefList=function(d,b,c,a){c=this.executor.executeMethod("GetTaskdefList","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.TaskInsID=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetVariableList=function(d,b,c,a){c=this.executor.executeMethod("GetVariableList","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},
a.TaskInsID=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetVariableListDS=function(d,b,c,a){c=this.executor.executeMethod("GetVariableListDS","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.TaskInsID=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetTaskdefListDS=function(d,b,c,a){c=this.executor.executeMethod("GetTaskdefListDS",
"GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.TaskInsID=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetWorkFlowChart=function(d,b,c,a,e){a=this.executor.executeMethod("GetWorkFlowChart","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.FlowID=d,e.isDef=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=
a.cmdIndex),e):a};this.GetTaskListDS=function(d,b,c,a,e,f){e=this.executor.executeMethod("GetTaskListDS","GET",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&null!=e.result&&isArray(e.result)?(a=e.result,f={},f.AUserID=d,f.ACompletedState=b,f.AOtherCondition=c,f.result=a[0],null!=e.cacheId&&null!=e.cmdIndex&&(f._cacheId=e.cacheId,f._cmdIndex=e.cmdIndex),f):e};this.TaskCanUpdate=function(d,b,c,a){c=this.executor.executeMethod("TaskCanUpdate","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&
isArray(c.result))&&(b=c.result,c={},c.TaskInsID=d,c.result=b[0]),c}}
function TMessageManage(l){this.executor=new ServerFunctionExecutor("TMessageManage",l);this.NewMessageGroup=function(d,b,c,a,e){this.executor.executeMethod("NewMessageGroup","GET",[d,b],c,!1,a,e)};this.DelMessageGroup=function(d,b,c,a){this.executor.executeMethod("DelMessageGroup","GET",[d],b,!1,c,a)};this.UpdateMessageGroup=function(d,b,c,a,e,f){this.executor.executeMethod("MessageGroup","POST",[d,b,c],a,!1,e,f)};this.NewMessageMember=function(d,b,c,a,e,f){this.executor.executeMethod("NewMessageMember",
"GET",[d,b,c],a,!1,e,f)};this.UpdateMessageMember=function(d,b,c,a,e,f){this.executor.executeMethod("MessageMember","POST",[d,b,c],a,!1,e,f)};this.DelMessageMember=function(d,b,c,a,e){this.executor.executeMethod("DelMessageMember","GET",[d,b],c,!1,a,e)};this.GetMessageGroupList=function(d,b,c){b=this.executor.executeMethod("GetMessageGroupList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=
b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetGroupMemberList=function(d,b,c,a){c=this.executor.executeMethod("GetGroupMemberList","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.GroudId=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetAllEmployee=function(d,b,c,a){c=this.executor.executeMethod("GetAllEmployee","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?
(b=c.result,a={},a.GroupId=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.IsGroupMember=function(d,b,c,a,e){a=this.executor.executeMethod("IsGroupMember","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.GroupId=d,a.MemberId=b,a.result=c[0]),a};this.GetUserList=function(d,b,c){b=this.executor.executeMethod("GetUserList","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?
(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetHTMLEscapedString=function(d,b,c,a){c=this.executor.executeMethod("GetHTMLEscapedString","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.Value=d,c.result=b[0]),c};this.UpdateCurUserCallbackClientID=function(d,b,c,a){c=this.executor.executeMethod("CurUserCallbackClientID","POST",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=
c.result&&isArray(c.result))&&(b=c.result,c={},c.Value=d,c.result=b[0]),c};this.SendMessageToAll=function(d,b,c,a){c=this.executor.executeMethod("SendMessageToAll","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.Msg=d,c.result=b[0]),c};this.SendMessageToUser=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToUser","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.UserID=
b,a.result=c[0]),a};this.SendMessageToDepartment=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToDepartment","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.DepartmentID=b,a.result=c[0]),a};this.SendMessageToGroup=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToGroup","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.GroupID=b,a.result=c[0]),
a};this.SendMessageToJob=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToJob","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.JobID=b,a.result=c[0]),a};this.SendMessageToRole=function(d,b,c,a,e){a=this.executor.executeMethod("SendMessageToRole","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.Msg=d,a.RoleID=b,a.result=c[0]),a};this.SendMessageToFollow=function(d,
b,c,a){c=this.executor.executeMethod("SendMessageToFollow","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.Msg=d,c.result=b[0]),c};this.SendCMDToFollow=function(d,b,c,a){c=this.executor.executeMethod("SendCMDToFollow","GET",[d],b,!0,c,a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.cmdStr=d,c.result=b[0]),c};this.SendCMDToAll=function(d,b,c,a){c=this.executor.executeMethod("SendCMDToAll","GET",[d],b,!0,c,
a);if(null==b)return null!=c&&(null!=c.result&&isArray(c.result))&&(b=c.result,c={},c.cmdStr=d,c.result=b[0]),c};this.SendCMDToUser=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToUser","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.UserID=b,a.result=c[0]),a};this.SendCMDToDepartment=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToDepartment","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&
isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.DepartmentID=b,a.result=c[0]),a};this.SendCMDToGroup=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToGroup","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.GroupID=b,a.result=c[0]),a};this.SendCMDToJob=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToJob","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=
d,a.JobID=b,a.result=c[0]),a};this.SendCMDToRole=function(d,b,c,a,e){a=this.executor.executeMethod("SendCMDToRole","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.cmdStr=d,a.RoleID=b,a.result=c[0]),a};this.SendMgrMessage=function(d,b,c,a,e){a=this.executor.executeMethod("SendMgrMessage","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&(null!=a.result&&isArray(a.result))&&(c=a.result,a={},a.itype=d,a.Msg=b,a.result=c[0]),a};this.SendMissMessage=
function(d,b,c,a){this.executor.executeMethod("SendMissMessage","GET",[d],b,!1,c,a)};this.GetLatelyMessage=function(d,b,c,a,e,f){e=this.executor.executeMethod("GetLatelyMessage","GET",[d,b,c],a,!0,e,f);if(null==a)return null!=e&&null!=e.result&&isArray(e.result)?(a=e.result,f={},f.UserId=d,f.ReceId=b,f.RecType=c,f.result=a[0],null!=e.cacheId&&null!=e.cmdIndex&&(f._cacheId=e.cacheId,f._cmdIndex=e.cmdIndex),f):e};this.SendMissMessageToUser=function(d,b,c,a,e,f,h,g){h=this.executor.executeMethod("SendMissMessageToUser",
"GET",[d,b,c,a,e],f,!0,h,g);if(null==f)return null!=h&&(null!=h.result&&isArray(h.result))&&(f=h.result,h={},h.Msg=d,h.FromID=b,h.FromName=c,h.MsgID=a,h.sendtime=e,h.result=f[0]),h};this.SendMissMessageToDepartment=function(d,b,c,a,e,f,h,g,j){g=this.executor.executeMethod("SendMissMessageToDepartment","GET",[d,b,c,a,e,f],h,!0,g,j);if(null==h)return null!=g&&(null!=g.result&&isArray(g.result))&&(h=g.result,g={},g.Msg=d,g.FromID=b,g.FromName=c,g.DepartmentID=a,g.MsgID=e,g.sendtime=f,g.result=h[0]),
g};this.SendMissMessageToGroup=function(d,b,c,a,e,f,h,g,j){g=this.executor.executeMethod("SendMissMessageToGroup","GET",[d,b,c,a,e,f],h,!0,g,j);if(null==h)return null!=g&&(null!=g.result&&isArray(g.result))&&(h=g.result,g={},g.Msg=d,g.FromID=b,g.FromName=c,g.GroupID=a,g.MsgID=e,g.sendtime=f,g.result=h[0]),g}}
function TContractProject(l){this.executor=new ServerFunctionExecutor("TContractProject",l);this.GetContype=function(d,b,c){b=this.executor.executeMethod("GetContype","GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetContlist=function(d,b,c,a,e){a=this.executor.executeMethod("GetContlist","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&
isArray(a.result)?(c=a.result,e={},e.userid=d,e.ctypeid=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.GetContdata=function(d,b,c,a){c=this.executor.executeMethod("GetContdata","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.contid=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.GetProtype=function(d,b,c){b=this.executor.executeMethod("GetProtype",
"GET",[],d,!0,b,c);if(null==d)return null!=b&&null!=b.result&&isArray(b.result)?(d={},d.result=b.result[0],null!=b.cacheId&&null!=b.cmdIndex&&(d._cacheId=b.cacheId,d._cmdIndex=b.cmdIndex),d):b};this.GetProlist=function(d,b,c,a,e){a=this.executor.executeMethod("GetProlist","GET",[d,b],c,!0,a,e);if(null==c)return null!=a&&null!=a.result&&isArray(a.result)?(c=a.result,e={},e.userid=d,e.ProTypeid=b,e.result=c[0],null!=a.cacheId&&null!=a.cmdIndex&&(e._cacheId=a.cacheId,e._cmdIndex=a.cmdIndex),e):a};this.GetProdata=
function(d,b,c,a){c=this.executor.executeMethod("GetProdata","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.Projectid=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c}}
function THouseView(l){this.executor=new ServerFunctionExecutor("THouseView",l);this.GetHouseViewStream=function(d,b,c,a){c=this.executor.executeMethod("GetHouseViewStream","GET",[d],b,!0,c,a);if(null==b)return null!=c&&null!=c.result&&isArray(c.result)?(b=c.result,a={},a.AKeyID=d,a.result=b[0],null!=c.cacheId&&null!=c.cmdIndex&&(a._cacheId=c.cacheId,a._cmdIndex=c.cmdIndex),a):c};this.UpdateHouseViewFile=function(d,b,c,a,e,f){e=this.executor.executeMethod("HouseViewFile","POST",[d,b,c],a,!0,e,f);
if(null==a)return null!=e&&(null!=e.result&&isArray(e.result))&&(a=e.result,e={},e.AKeyID=d,e.AFileName=b,e.AStream=c,e.result=a[0]),e}}
var JSProxyClassList={DSAdmin:"GetPlatformName ClearResources FindPackages FindClasses FindMethods CreateServerClasses DropServerClasses CreateServerMethods DropServerMethods GetServerClasses ListClasses DescribeClass ListMethods DescribeMethod GetServerMethods GetServerMethodParameters GetDatabaseConnectionProperties GetDSServerName ConsumeClientChannel ConsumeClientChannelTimeout CloseClientChannel RegisterClientCallbackServer UnregisterClientCallback BroadcastToChannel BroadcastObjectToChannel NotifyCallback NotifyObject".split(" "),TLoginUser:"GetSysConnectionString ChangePassword UpdateCurUserCallbackClientID Logout SetUsersToFollow SendMessageToFollow SendMessageToAll SendMessageToUser SendMessageToDepartment SendMessageToGroup SendCMDToFollow SendCMDToAll SendCMDToUser SendCMDToDepartment SendCMDToGroup SendMgrMessage GetAccList GetCurUserInfo ListOfLoginUser ListOfAllLoginUser GetClassList GetAutoCodeFields GetModuleData RefreshGlobeVar GetModuleRight GetAccInforJSON GetAccListJSON GetCurUserJSON GetUserList GetAllUserList GetClassListJO GetAutoCodeFieldsJO GetModuleDataJO RefreshGlobeVarJO GetModuleRightJO GetDepartmentAndUsersList UserIdToName GetServerInfo GetFtpSetting GetMailSetting GetSmsSetting GetWorkFlowServerList GetSmsServerList".split(" "),
TSyAccBook:["GetAllAccBook","GetActiveAccBook","GetAllAccBookJO","GetActiveAccBookJO"],TServerDataSet:"GetInitResult Open Update Delete DeleteDetail CmdExec Check CloseOff Revoke Tally ExecSQL ValidateData QueryOpen QueryExecSQL QuerySysOpen QuerySysExecSQL".split(" "),TServerQuery:"QueryOpen QueryExecSQL ExecSQL QuerySysOpen QuerySysExecSQL SysExecSQL".split(" "),TJServerDataSet:"GetInitResult Open Update Delete DeleteDetail ValidateData CmdExec Check CloseOff Revoke Tally ExecSQL QueryOpen QueryExecSQL QuerySysOpen QuerySysExecSQL".split(" "),
TJServerQuery:["QueryOpen","QueryUpdate","QueryExecSQL","QuerySysOpen","QuerySysExecSQL"],TWorkFlowServer:"ServerWorkFlowStartJSON ServerWorkFlowStart ServerWorkFlowExecJSON ServerWorkFlowExec GetTaskList GetLogList GetDiagram GetTaskdefList GetVariableList GetVariableListDS GetTaskdefListDS GetWorkFlowChart GetTaskListDS TaskCanUpdate".split(" "),TMessageManage:"NewMessageGroup DelMessageGroup UpdateMessageGroup NewMessageMember UpdateMessageMember DelMessageMember GetMessageGroupList GetGroupMemberList GetAllEmployee IsGroupMember GetUserList GetHTMLEscapedString UpdateCurUserCallbackClientID SendMessageToAll SendMessageToUser SendMessageToDepartment SendMessageToGroup SendMessageToJob SendMessageToRole SendMessageToFollow SendCMDToFollow SendCMDToAll SendCMDToUser SendCMDToDepartment SendCMDToGroup SendCMDToJob SendCMDToRole SendMgrMessage SendMissMessage GetLatelyMessage SendMissMessageToUser SendMissMessageToDepartment SendMissMessageToGroup".split(" "),
TContractProject:"GetContype GetContlist GetContdata GetProtype GetProlist GetProdata".split(" "),THouseView:["GetHouseViewStream","UpdateHouseViewFile"]};
